### ISSUE TITLE
How to set weather and flight altitude

### ISSUE THREAD

**Issue by ZERO-15** [SASLabStevens/MASC-Architecture#3]
Dear author
I want to reproduce the experiment in your video, but your readme doesn't explain how to set flight altitude and weather. Could you tell me how to set it up？

**Comment by robotics-dotcom** [comment]
Thank you for your question. Sorry for replying you late :). Please feel free to [refer this repository](https://github.com/haotiangu/XPlaneConnect) to put the airplane to specific localization. As for the weather configuration, please feel free to configure in X-PLANE 11. Any question and comments are welcome. Feel free to email me.

**Comment by ZERO-15** [comment]
Thanks, but this [refer this repository](https://github.com/haotiangu/XPlaneConnect) page can't found (404). Maybe it's a private page.

**Comment by robotics-dotcom** [comment]
https://github.com/haotiangu/XPlaneConnect

**Comment by robotics-dotcom** [comment]
Thank you for reminding me. I did not realize it was set up as private. Now it is open.

**Comment by ZERO-15** [comment]
Thanks  👍
